sudo: required
services:
  - docker

before_install:
  - docker build -t NolanMagee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true NolanMagee/react-test npm test

after_success:
  - docker build -t NolanMagee/multi-client ./client
  - docker build -t NolanMagee/multi-nginx ./nginx
  - docker build -t NolanMagee/multi-server ./server
  - docker build -t NolanMagee/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push NolanMagee/multi-client
  - docker push NolanMagee/multi-nginx
  - docker push NolanMagee/multi-server
  - docker push Nolanmagee/multi-worker
